runtime: java
env: flex

handlers:
- url: /.*
  script: this field is required, but ignored

# [START env_variables]
env_variables:
  SENDGRID_API_KEY: YOUR-SENDGRID-API-KEY
  SENDGRID_SENDER: YOUR-SENDGRID-SENDER
# [END env_variables]
